In [1]:
import numpy as np

In [2]:
one_1D=np.array([1,2,3])
print(one_1D)

[1 2 3]


In [3]:
type(one_1D)

numpy.ndarray

In [4]:
one_1D.ndim

1

In [5]:
twoD=np.array([[1,2,3],[4,5,6]])
print(twoD)

[[1 2 3]
 [4 5 6]]


In [6]:
type(twoD)

numpy.ndarray

In [7]:
twoD.ndim

2

In [8]:
twoD.shape

(2, 3)

In [9]:
twoD.size


6

In [10]:
twoD.dtype


dtype('int32')