In [1]:
import numpy as np

In [2]:
#one's matrix

In [3]:
ones=np.ones(3)
print(ones) #default dtype is float

[1. 1. 1.]


In [4]:
ones=np.ones((3,5))
print(ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [5]:
ones=np.ones((3,5),dtype=int)
print(ones)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [6]:
ones=np.ones((3,5),dtype=str)
print(ones)

[['1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1']]


In [7]:
ones=np.ones((3,5),dtype=bool)
print(ones)

[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [8]:
ones.size

15

In [9]:
ones.shape

(3, 5)

In [10]:
#zeros matrix

In [11]:
zero=np.zeros(5)
print(zero)

[0. 0. 0. 0. 0.]


In [12]:
zero=np.zeros((3,5))
print(zero)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [13]:
zero=np.zeros((3,5),dtype=int)
print(zero)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [14]:
zero=np.zeros((3,5),dtype=str)
print(zero)

[['' '' '' '' '']
 ['' '' '' '' '']
 ['' '' '' '' '']]


In [15]:
zero=np.zeros((3,5),dtype=bool)
print(zero)

[[False False False False False]
 [False False False False False]
 [False False False False False]]


In [16]:
#empty matrix

In [17]:
empty=np.empty(5)
print(empty)

[0. 0. 0. 0. 0.]


In [18]:
empty=np.empty((3,3))
print(empty) #it will print random values

[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 7.78647458e-321]
 [1.05675390e-311 1.05675390e-311 1.05708216e-311]]


In [19]:
empty=np.empty((3,3),dtype=int)
print(empty) #it will print random values

[[      0       1       0]
 [7077985    1132       0]
 [    768     498 6029427]]


In [20]:
empty=np.empty((3,3),dtype=str)
print(empty) #it will print random values

[['' '' '']
 ['' '' '']
 ['' '' '']]


In [21]:
empty=np.empty((3,3),dtype=bool)
print(empty) #it will print random values

[[False False False]
 [False False  True]
 [ True  True  True]]
