#  Python NumPy array concatenation and split

In [1]:
import numpy as np

the list can be concatenate using + but array cann't

In [2]:
arr1=np.arange(1,17).reshape(4,4)
print(f'first array\n {arr1}')
print()
arr2=np.arange(17,33).reshape(4,4)
print(f'second array\n {arr2}')

first array
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

second array
 [[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [3]:
lst1=[1,2,3]
lst2=[4,5,6]
print(lst1,lst2)

[1, 2, 3] [4, 5, 6]


concatinating this two strings using + operator

In [4]:
lst1+lst2

[1, 2, 3, 4, 5, 6]

if we try to concatenate the array like this it will be the sum of array by elements

/*to concatenate the array we have to use the np.concatenate() method */

In [5]:
np.concatenate((arr1,arr2))
# it will be column wise concatenation becuase default axis is 0

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

row wise concatenation

In [6]:
np.concatenate((arr1,arr2),axis=1)
# it will be row wise concatenation becuase  axis is 1

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

we can use another method to concatenate the array as vertically or horizontally

In [7]:
np.vstack((arr1,arr2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [8]:
np.hstack((arr1,arr2))

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

np.split(), this method is used to broke or divide the array into parts by using given seperator
default axis is 0 so it will split by column
it will split the array in given parts in the list form and elements will np.ndarray

In [9]:
a=np.split(arr1,2)
print(a)
#it will split the array in 2 parts

[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])]


In [10]:
print(type(a))

<class 'list'>


In [11]:
b=np.split(arr1,4,axis=1)
print(b)
#it will split the array in 4 parts in row wise

[array([[ 1],
       [ 5],
       [ 9],
       [13]]), array([[ 2],
       [ 6],
       [10],
       [14]]), array([[ 3],
       [ 7],
       [11],
       [15]]), array([[ 4],
       [ 8],
       [12],
       [16]])]


working with oneD array

In [12]:
d1=np.array([2,6,12,9])
print(d1)

[ 2  6 12  9]


In [13]:
np.split(d1,[1,3])
#it will split the d1 array in 3 parts as list of array
#the first array wull hold all the values before 1  , second will hold the values before 3 and rest will be in last array

[array([2]), array([ 6, 12]), array([9])]