In [1]:
import numpy as np

In [2]:
arr1=np.arange(1,101).reshape(10,10)
print(arr1)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


#### reading column/ rows wise using slicing the array

In [3]:
a=arr1[4,5] #index starts from 0
print(a)

46


##### this value has no dimension, means this is scaler

In [4]:
a.ndim 

0

In [5]:
a=arr1[0]
print(a) #this is first row and it will be in form of array
print(a.ndim) #this is 1d array

[ 1  2  3  4  5  6  7  8  9 10]
1


#### only one column but all rows

In [6]:
a=arr1[:,0]
print(a)
a.ndim

[ 1 11 21 31 41 51 61 71 81 91]


1

###### value in multid

In [7]:
a=arr1[:,0:1] #all rows in 2d
print(a)
a.ndim

[[ 1]
 [11]
 [21]
 [31]
 [41]
 [51]
 [61]
 [71]
 [81]
 [91]]


2

In [8]:
a=arr1[1:4,0] #from 1 row to 3rd of 1st column
print(a)
a.ndim

[11 21 31]


1

In [9]:
a=arr1[1:4,0:4] #from 1 row to 3rd and 0th column to 3th column
print(a)
a.ndim

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


2

In [12]:
a=arr1[5:9,5:9]
print(a)
a.ndim

[[56 57 58 59]
 [66 67 68 69]
 [76 77 78 79]
 [86 87 88 89]]


2

###### accessing whole matrix

In [16]:
arr1

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [17]:
arr1[::]

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [27]:
arr1[:,:]

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [24]:
a=arr1[6:9,6:9]
print(a)
a.ndim

[[67 68 69]
 [77 78 79]
 [87 88 89]]


2

In [25]:
a=arr1[:5,5:]
print(a)
a.ndim

[[ 6  7  8  9 10]
 [16 17 18 19 20]
 [26 27 28 29 30]
 [36 37 38 39 40]
 [46 47 48 49 50]]


2

###### item size attribute

In [28]:
arr1.itemsize #means 4 byte

4

In [30]:
arr1.dtype #means 4 byte, 1byte =8bit 4*8=32 bit

dtype('int32')