# numpy  functions

In [1]:
import numpy as np

### arange()
numpy.arange([start, ]stop, [step, ]dtype=None, *, like=None)

Return evenly spaced values within a given interval.

In [2]:
arr1d=np.arange(1,10)
arr1d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr1d=np.arange(1,10,2) #with 2 steps
arr1d

array([1, 3, 5, 7, 9])

In [4]:
arr1d.size

5

In [5]:
arr1d.ndim

1

In [6]:
arr1d.shape

(5,)

In [7]:
evenarr=np.arange(2,50,2) #from 2 to 49 with 2 steps

In [8]:
evenarr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48])

### linspace()
numpy.linspace
numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)[source]
Return evenly spaced numbers over a specified interval.

Returns num evenly spaced samples, calculated over the interval [start, stop].

The endpoint of the interval can optionally be excluded.
mtlb diya hua value ke bich me same difference no generate krke dega
(2,4,10) mtlb 2 se 4 ke bich me 10 value dega ekdum same difference ke sath

In [9]:
arrlin=np.linspace(2,4)

In [10]:
arrlin

array([2.        , 2.04081633, 2.08163265, 2.12244898, 2.16326531,
       2.20408163, 2.24489796, 2.28571429, 2.32653061, 2.36734694,
       2.40816327, 2.44897959, 2.48979592, 2.53061224, 2.57142857,
       2.6122449 , 2.65306122, 2.69387755, 2.73469388, 2.7755102 ,
       2.81632653, 2.85714286, 2.89795918, 2.93877551, 2.97959184,
       3.02040816, 3.06122449, 3.10204082, 3.14285714, 3.18367347,
       3.2244898 , 3.26530612, 3.30612245, 3.34693878, 3.3877551 ,
       3.42857143, 3.46938776, 3.51020408, 3.55102041, 3.59183673,
       3.63265306, 3.67346939, 3.71428571, 3.75510204, 3.79591837,
       3.83673469, 3.87755102, 3.91836735, 3.95918367, 4.        ])

In [11]:
arrlin=np.linspace(2,4,100) #ye 2 se 4 ke bich me 100 value dega with same difference

In [12]:
arrlin

array([2.        , 2.02020202, 2.04040404, 2.06060606, 2.08080808,
       2.1010101 , 2.12121212, 2.14141414, 2.16161616, 2.18181818,
       2.2020202 , 2.22222222, 2.24242424, 2.26262626, 2.28282828,
       2.3030303 , 2.32323232, 2.34343434, 2.36363636, 2.38383838,
       2.4040404 , 2.42424242, 2.44444444, 2.46464646, 2.48484848,
       2.50505051, 2.52525253, 2.54545455, 2.56565657, 2.58585859,
       2.60606061, 2.62626263, 2.64646465, 2.66666667, 2.68686869,
       2.70707071, 2.72727273, 2.74747475, 2.76767677, 2.78787879,
       2.80808081, 2.82828283, 2.84848485, 2.86868687, 2.88888889,
       2.90909091, 2.92929293, 2.94949495, 2.96969697, 2.98989899,
       3.01010101, 3.03030303, 3.05050505, 3.07070707, 3.09090909,
       3.11111111, 3.13131313, 3.15151515, 3.17171717, 3.19191919,
       3.21212121, 3.23232323, 3.25252525, 3.27272727, 3.29292929,
       3.31313131, 3.33333333, 3.35353535, 3.37373737, 3.39393939,
       3.41414141, 3.43434343, 3.45454545, 3.47474747, 3.49494

In [13]:
arrlin=np.linspace(2,20,10)

In [14]:
arrlin

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [15]:
arrlin=np.linspace(2,20,10,)

In [16]:
arrlin

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

### reshape() arr.reshape(row,column)  --> for 3d--> arr.reshape(3d,2d,1d)
Gives a new shape to an array without changing its data.
It is not always possible to change the shape of an array without copying the data. If you want an error to be raised when the data is copied, you should assign the new shape to the shape attribute of the array:

In [17]:
original_arr1d=np.arange(2,20,3)
original_arr1d

array([ 2,  5,  8, 11, 14, 17])

In [18]:
original_arr1d.size 

6

####  as the size is six so that we can reshape it into another dimension like 2x3, 3x2, 1x6, 6x1, 3x2x1, 1x2x3, 2x3x1, 3x1x2 these are all possible shapes

In [19]:
original_arr1d.reshape(2,3)

array([[ 2,  5,  8],
       [11, 14, 17]])

In [20]:
original_arr1d.reshape(3,2)

array([[ 2,  5],
       [ 8, 11],
       [14, 17]])

In [21]:
original_arr1d.reshape(1,6)

array([[ 2,  5,  8, 11, 14, 17]])

In [22]:
original_arr1d.reshape(6,1)

array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]])

In [23]:
original_arr1d.reshape(1,2,3)

array([[[ 2,  5,  8],
        [11, 14, 17]]])

In [24]:
original_arr1d.reshape(1,3,2)

array([[[ 2,  5],
        [ 8, 11],
        [14, 17]]])

In [25]:
original_arr1d.reshape(2,1,3)

array([[[ 2,  5,  8]],

       [[11, 14, 17]]])

In [26]:
original_arr1d.reshape(2,3,1)

array([[[ 2],
        [ 5],
        [ 8]],

       [[11],
        [14],
        [17]]])

In [27]:
original_arr1d.reshape(3,1,2)

array([[[ 2,  5]],

       [[ 8, 11]],

       [[14, 17]]])

In [28]:
original_arr1d.reshape(3,2,1)

array([[[ 2],
        [ 5]],

       [[ 8],
        [11]],

       [[14],
        [17]]])

In [29]:
a = np.arange(36).reshape((2,6,3))

In [30]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

### ndarray.flat
### 1-D iterator over an array.

### ndarray.flatten
### 1-D array copy of the elements of an array in row-major order.

### ndarray.reshape
### Change the shape of an array without changing its data.

### ravel()
#### multi d array ko 1d me convert krta hai
numpy.ravel
numpy.ravel(a, order='C')[source]
Return a contiguous flattened array.

A 1-D array, containing the elements of the input, is returned. A copy is made only if needed.

As of NumPy 1.10, the returned array will have the same type as the input array. (for example, a masked array will be returned for a masked array input)

In [31]:
a = np.arange(10).reshape((5,2))

In [32]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [33]:
a.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### flattern()
ndarray.flatten(order='C')
Return a copy of the array collapsed into one dimension.

In [34]:
a = np.arange(30).reshape((5,2,3))

In [35]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29]]])

In [36]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

### transpose row ko column and column ko row me
numpy.transpose(a, axes=None)[source]
Reverse or permute the axes of an array; returns the modified array.

For an array a with two axes, transpose(a) gives the matrix transpose.

Refer to numpy.ndarray.transpose for full documentation.

In [37]:
a = np.arange(10).reshape((5,2))

In [38]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [39]:
a.shape

(5, 2)

In [40]:
b=a.transpose()

In [41]:
b

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [42]:
b.shape

(2, 5)

In [48]:
a=b.T #T is also used to transpose the matrix

In [46]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [47]:
a.shape

(5, 2)