In [1]:
import numpy as np

In [2]:
array1=np.arange(1,10).reshape(3,3)
array2=np.arange(1,10).reshape(3,3)

In [3]:
array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

###  addition using + (element wise)


In [5]:
array1+array2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [6]:
array1-array2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

###  np.add(arr1,arr2)
### np.subtracr(arr1,arr2)

In [7]:
np.add(array1,array2)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [8]:
np.subtract(array1,array2)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

### * AND /  -- OR np.multiply or divide 

In [9]:
array1*array2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [10]:
array1/array2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.multiply(array1,array2)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [12]:
np.divide(array1,array2)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

####  matrix production means row x column wise

In [13]:
array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
array1 @ array2

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [16]:
array1.dot(array2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

### maximum and minimun value from the matrix and to find the index of that value

In [17]:
array1.max()

9

In [18]:
array1.min()

1

In [19]:
array1.argmax()

8

In [20]:
array1.argmin()

0

###  using axis we can find the max and min from every row/ column -> 0 is column and 1 is row

In [21]:
arr= np.arange(2,50,4).reshape(3,4)

In [22]:
arr

array([[ 2,  6, 10, 14],
       [18, 22, 26, 30],
       [34, 38, 42, 46]])

In [23]:
arr.max(axis=1)

array([14, 30, 46])

In [24]:
arr.argmax(axis=1)

array([3, 3, 3], dtype=int64)

In [25]:
arr.min(axis=1)

array([ 2, 18, 34])

In [26]:
arr.argmin(axis=1)

array([0, 0, 0], dtype=int64)

In [27]:
arr.min(axis=0)

array([ 2,  6, 10, 14])

In [28]:
arr.argmin(axis=0)

array([0, 0, 0, 0], dtype=int64)

In [29]:
arr.argmax(axis=0)

array([2, 2, 2, 2], dtype=int64)

### to find the sum of all elements of the matrix

In [30]:
arr

array([[ 2,  6, 10, 14],
       [18, 22, 26, 30],
       [34, 38, 42, 46]])

In [31]:
np.sum(arr)

288

#### sum using axis wise

In [32]:
arr=np.arange(1,10).reshape(3,3)

In [33]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
np.sum(arr,axis=0)

array([12, 15, 18])

In [35]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [36]:
np.sum(arr,axis=0)

array([12, 15, 18])

### mean()

In [37]:
arr.mean()

5.0

#### np.sqrt()

In [38]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

#### standard division np.std()

In [39]:
np.std(arr)

2.581988897471611

### exponent np.exp()

In [40]:
np.exp(arr)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

### np.log()

In [41]:
np.log(arr)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

###  log base 10 , np.log10()

In [42]:
np.log10(arr)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])